name: Clang-Format-Checks

on: [ push ]

jobs:
  clang-format-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Install clang-format
        run: sudo apt-get install clang-format

      - uses: actions/checkout@v2

      - name: Check format
        working-directory: ${{github.workspace}}
        shell: bash
        run: clang-format include/mabe/locked.hpp --dry-run --Werror
